### ISSUE TITLE
Question: How to utilize folder 

### ISSUE THREAD

**Issue by kaztakata** [vneecious/sap-cap-sdm-plugin#15]
Hello @vneecious 
Thanks for your great contribution to this module.

I tried to use your module and verified in simple CRUD scenario. I am excited with the result :)
Next step, I would like to go to utilize SDM folder to categorize files like below, and am stuck.

```
root - folder:A - file X
                - file Y
root - folder:B - file Z
```

Then I read your code and found relevant ones in [onRead](https://github.com/vneecious/sap-cap-sdm-plugin/blob/master/lib/handlers/index.js#L43) and [onCreate](https://github.com/vneecious/sap-cap-sdm-plugin/blob/master/lib/handlers/index.js#L137). 
Both are using [deriveFolderNameFromNavigation](https://github.com/vneecious/sap-cap-sdm-plugin/blob/master/lib/util/index.js#L51), but I cannot see which path is applicable for creating folder.

Would you provide me sample data model or something else to utilize folder?

**Comment by vneecious** [comment]
Hi @kaztakata! Thank you for your comment.

By using the `Sdm` annotations, the only way to generate folders is by creating some association with another entity. For example, if you `@Sdm.Entity` is `Avatars` and it belongs to a parent entity `Users`, when uploading a new image for a user, the plugin will always create a folder for the given user and add the related image under this folder. That's why I have this `deriveFolderNameFromNavigation`, so I can extract the folder name from the parent entity. So, when `GET /Users('123')/avatar` is used, the plugin will look for the file that is under the folder `root/Users-123`.

Take a look at the [test/entity-association](https://github.com/vneecious/sap-cap-sdm-plugin/tree/c132a042791b9505f781d06a745ed679642ce9c5/test/crud/entity-association) so you can have a clearer example of what I'm saying.

If you want to take more control over these things, generate more subdirectories, or do something else that the `Sdm` annotations don't support, you can remove them and implement your own logic by using the `cmis-client` API.

For example, if you want to create a folder using the cmis-client, instead of letting the plugin do it automatically, you could:

```javascript
    const { repositoryId } = getSettings(); // const { getSettings } = require('sap-cap-sdm-plugin/lib/settings');
    const destination = await loadDestination(req); // const { loadDestination } = require('sap-cap-sdm-plugin/lib/destination');

    const cmisClient = await cds.connect.to('cmis-client');
    const newFolder = await cmisClient
      .createFolder(repositoryId, folderName)
      .execute(destination);
  });
```

Take a look at the [cmis-client](https://github.com/vneecious/sap-cap-sdm-plugin/blob/c132a042791b9505f781d06a745ed679642ce9c5/srv/cmis/client.js) for more methods and how to use them.

**Comment by kaztakata** [comment]
Hi @vneecious,

Thanks for your quick comment. I tried [test/entity-association](https://github.com/vneecious/sap-cap-sdm-plugin/tree/c132a042791b9505f781d06a745ed679642ce9c5/test/crud/entity-association) and actually avatar file is created on `/Users:1` folder.
I would like to close this issue and post next issue.
