### ISSUE TITLE
Can't Create Document into folder

### ISSUE THREAD

**Issue by mcselvan** [vneecious/sap-cap-sdm-plugin#18]
Actual Requirement is I want to a create document inside "/root/manifolder/subfolder1" folder and passing the same path as optional to createdocument function but during the runtime openapi encoding the path like "/root%2Fmainfolder%2Fsubfolder1". due to this, it throws error like CSRF token verification failed.  

Even @sap-cloud-sdk/openapi support team also couldn't fix it..

**Comment by mcselvan** [comment]
I discovered an error in the way query parameters are encoded. Currently, they are transmitted in their raw form without encoding, causing issues with the Open API. Specifically, the API doesn't accept unencoded values for the {directoryPath} parameter. To resolve this, we need to implement proper URL encoding for all query parameters before sending the request. This will ensure compatibility with the Open API and prevent further errors. Please prioritize fixing this issue as soon as possible.

mcselvan03_0-1707452575819.png

**Comment by vneecious** [comment]
In other words, we should get rid of the `OpenApiRequestBuilder` and implement our own. 
I'll dig into this and tell you when I have a test version.
Thanks for this finding. It was extremely valuable.

**Comment by vneecious** [comment]
Ok, so basically, the `OpenApiRequestBuilder` was encoding all the dynamic query parameters for obvious reasons. The problem is that in our case, we literally want a URI path, so the URL became something like `http://sdm/root/dirpath/dirpath/dirpath`. So, the easiest way I found was to [extend the `OpenApiRequestBuilder` class and replace the implementation of getPath](https://github.com/vneecious/sap-cap-sdm-plugin/blob/260f844c221026e01eda6355fa003923bba314ef/srv/cmis/request-builders.js#L3) - which is where all this encoding happens - with a new one that prevents the `directoryPath` parameter from being URI-encoded.

I also added [a test case](https://github.com/vneecious/sap-cap-sdm-plugin/blob/260f844c221026e01eda6355fa003923bba314ef/test/cmis/basic-repository.test.js#L144) to validate this fix, and it seems it worked fine.

That's probably not the best approach possible because `getPath` is private, but for now, I think it is good enough.

Thanks again for you finding and sorry for the delayed response.
